---
title: "R Notebook"
output: html_notebook
---

```{r}
#load packages
library(readxl)
library(tidyverse)
library(here)
library(corrplot)
library(ggthemes)
library(lubridate)
library(zoo)
library(forecast)
library(tseries)
library(ggplot2)
library(lubridate)
library(tidyverse)
library(ggthemes)
library(dplyr)
library(cowplot)
```

```{r, import data}
flat_inflow_monthly <- read_excel("Data/Hydrology_Assignment1_FallsLake.xlsx", 
    sheet = "Flat River Month flow data (in)")
eno_inflow_monthly <- read_excel("Data/Hydrology_Assignment1_FallsLake.xlsx", 
    sheet = "Eno River Month flow data (in)")
neuse_outflow_monthly <- read_excel("Data/Hydrology_Assignment1_FallsLake.xlsx", 
    sheet = "Neuse River flow data (out)")

# create date column
eno_inflow_monthly$Date <- make_date(eno_inflow_monthly$year, eno_inflow_monthly$month, 1)
neuse_outflow_monthly$Date <- make_date(neuse_outflow_monthly$year, neuse_outflow_monthly$month, 1)
flat_inflow_monthly$Date <- make_date(flat_inflow_monthly$year, flat_inflow_monthly$month, 1)

# select total volume
eno.select <- select(eno_inflow_monthly, total_volume, Date) %>% 
  mutate(total_volume_ENO = eno_inflow_monthly$total_volume)

flat.select <- select(flat_inflow_monthly, total_volume, Date) %>% 
  mutate(total_volume_FLAT = flat_inflow_monthly$total_volume)

outflow <- neuse_outflow_monthly %>% 
  select(4,9) %>% 
  mutate(total_outflow = neuse_outflow_monthly$total_volume)

# create an inflow dataframe by merging eno and flat by date column, add inflows together, join with outflow
inflow_outflow <- eno.select[,2:3] %>%
  inner_join(flat.select[,2:3], by = "Date") %>% 
  mutate(total_inflow_volume = total_volume_ENO +total_volume_FLAT) %>% 
  inner_join(outflow[,2:3], by = "Date")
  
```

```{r, yearly flows}
mean_yearly_data <- inflow_outflow %>% 
  group_by(Year = year(Date)) %>% 
  summarise(
    Flat = mean(total_volume_FLAT),
    Eno = mean(total_volume_ENO),
    Yearly_Inflow = mean(total_inflow_volume),
    Yearly_Outflow = mean(total_outflow)) %>% 
  filter(Year >= 1985)
  
```

```{r, plot yearly flows}
YearlyInflowOutflow <- ggplot() +
  geom_line( aes(x = mean_yearly_data$Year, 
                 y= (mean_yearly_data$Yearly_Inflow)/100000000, 
                 color= 'Yearly Inflow'))+
   geom_line(aes(x = mean_yearly_data$Year, 
                 y= (mean_yearly_data$Yearly_Outflow)/100000000, 
                 color= 'Yearly Outflow')) +
  labs(
    title = "Total Inflow and Outflow Over Time",
    x = "Year",
    y = "Billions of cubic feet of water",
    color= "Legend", 
  ) +
  scale_x_continuous(breaks = seq(min(mean_yearly_data$Year), max(mean_yearly_data$Year), by = 5)) +  
  scale_y_continuous(breaks = seq(0, max(mean_yearly_data$Yearly_Inflow / 100000, mean_yearly_data$Yearly_Outflow / 100000), by = 5)) +  # Customize y-axis
  theme_minimal() +
  theme(legend.position = "top") 


YearlyInflowOutflow
  


```

```{r, plot yearly ENO inflow}
YearlyEno <- ggplot(eno_inflow_monthly, aes(x = year, 
                 y= total_volume/100000000)) +
  geom_line()+
  geom_smooth(method="lm")+
  labs(
    title = "Total Eno Inflow Over Time",
    x = "Year",
    y = "Billions of cubic feet of water"
  ) +
  #scale_x_continuous(breaks = seq(min(mean_yearly_data$Year), max(mean_yearly_data$Year), by = 5)) +  
  #scale_y_continuous(breaks = seq(0, max(mean_yearly_data$Eno), by = 5)) +  # Customize y-axis
  theme_minimal() 

YearlyEno
```

```{r}
YearlyFlat <- ggplot(flat_inflow_monthly, aes(x = year, 
                 y= total_volume/100000000)) +
  geom_line( )+
  geom_smooth(method= "lm")+
  labs(
    title = "Total Flat Inflow Over Time",
    x = "Year",
    y = "Billions of cubic feet of water"
  ) +
  #scale_x_continuous(breaks = seq(min(mean_yearly_data$Year), max(mean_yearly_data$Year), by = 5)) +  
  #scale_y_continuous(breaks = seq(0, max(mean_yearly_data$Eno), by = 1)) +  # Customize y-axis
  theme_minimal() 

YearlyFlat
```
